name = "Micrograd"
uuid = "44a974e8-869e-408e-aa13-b0ab7936f071"
authors = ["Vimarsh Sathia <vimarsh.sathia@gmail.com>"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
Plots = "1.40.9"
